title: "IST719 Information Visualization"
subtitle: "School of Information Studies, Syracuse University"
minimal_mistakes_skin: default
remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
search: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
